modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/mosharky/YonderCore/issues/" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://github.com/mosharky/YonderCore/" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="momo, Gareth"
description='''
A core mod for the Yonder modpack.
'''

[[mixins]]
config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[${neo_version},)" #mandatory
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="nomansland"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bountifulfares"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"